// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbuFLlhD5pimGpsNSBzt402pYccXf3Enw',
    appId: '1:996099906631:android:0685fe48b3d4a9b93d6562',
    messagingSenderId: '996099906631',
    projectId: 'listit-406411',
    storageBucket: 'listit-406411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpE0yuNIlXxZKGHo96XKuod65QxgQR0us',
    appId: '1:996099906631:ios:cfa50ea9cf9bc4dd3d6562',
    messagingSenderId: '996099906631',
    projectId: 'listit-406411',
    storageBucket: 'listit-406411.appspot.com',
    androidClientId: '996099906631-riatkq9aam2o2o15u1m8pho5es9ktiki.apps.googleusercontent.com',
    iosClientId: '996099906631-3jnni29e0j02sup10bpfm9vq6cd4fr9f.apps.googleusercontent.com',
    iosBundleId: 'com.armsgroup.lisitMobileApp',
  );
}
